---
- name: Change QRadar rule state
  hosts: qradar
  collections:
    - ibm.qradar

  tasks:
    - name: get info about qradar rule
      qradar_rule_info:
        name: "{{ rule_name }}"
      register: rule_info

    - name: change rule by id
      qradar_rule:
        state: "{{ rule_state }}"
        id: "{{ rule_info.rules[0]['id'] }}"
